apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer
  labels:
    app: producer
  namespace: kafka
spec:
  replicas: 3
  selector:
    matchLabels:
      app: producer
  template:
    metadata:
      labels:
        app: producer
    spec:
      containers:
      - name: producer
        image: producer:v0.0.1
        imagePullPolicy: IfNotPresent
