apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
  namespace: kafka
spec:
  containers:
  - name: ubuntu
    image: ubuntu:latest
    # Just spin & wait
    command: [ "/bin/bash", "-c", "--" ]
    args: [ "while true; do sleep 3000; done;" ]
