apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
  labels:
    app: database
  namespace: kafka
spec:
  replicas: 3
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
      - name: database
        image: database:v0.0.1
        imagePullPolicy: IfNotPresent
